stages:
  preprocess_fclip:
    cmd: >
      python dataset/weld.py
      --label_dir ${data.label_dir}
      --img_dir ${data.img_dir}
      --out_dir ${data.processed_dir}
      --val_ratio ${preprocess.val_ratio}
      --seed ${preprocess.seed}
      --angle_thresh ${preprocess.angle_thresh}
      --heatmap_resolution ${preprocess.heatmap_resolution}
      --input_resolution_h ${preprocess.input_resolution_h}
      --input_resolution_w ${preprocess.input_resolution_w}
    deps:
    - dataset/weld.py
    - ${data.label_dir}
    - ${data.img_dir}
    outs:
    - ${data.processed_dir}:
        cache: false

  train_fclip:
    cmd: >
      python -m FClip.train -d 0 -i HR config/model.yaml
      --params params.yaml
      --metrics_path metrics/metrics.json
    deps:
    - FClip
    - config/model.yaml
    - params.yaml
    - ${data.processed_dir}
    outs:
    - logs/IQI/${train.run_name}/checkpoint_best.pth.tar
    - logs/IQI/${train.run_name}/config.yaml
    metrics:
    - metrics/metrics.json

  gauge_preprocess:
    cmd: >
      python gauge/convert_to_yolo_obb.py
      --label_dir ${data.label_dir}
      --img_dir ${data.img_dir}
      --out_dir ${gauge_preprocess.out_dir}
      --val_ratio ${gauge_preprocess.val_ratio}
      --seed ${gauge_preprocess.seed}
      --class_name ${gauge_preprocess.class_name}
      --label_filter=${gauge_preprocess.label_filter}
    deps:
    - gauge/convert_to_yolo_obb.py
    - ${data.label_dir}
    - ${data.img_dir}
    outs:
    - ${gauge_preprocess.out_dir}:
        cache: false

  train_gauge:
    cmd: >
      python gauge/train.py
      --params params.yaml
      --augment ${gauge_train.augment}
      --metrics-path ${gauge_train.metrics_path}
    deps:
    - gauge/train.py
    - ${gauge_train.data}
    - ${gauge_train.model}
    - ${gauge_train.augment}
    - params.yaml
    - ${gauge_preprocess.out_dir}
    outs:
    - logs/gauge/${gauge_train.run_name}
    metrics:

    - ${gauge_train.metrics_path}
params:
- dvclive/params.yaml
metrics:
- dvclive/metrics.json
plots:
- dvclive/plots/metrics:
    x: step
- dvclive/plots/images
