stages:
  preprocess:
    cmd: >
      python dataset/weld.py
      --label_dir ${data.label_dir}
      --img_dir ${data.img_dir}
      --out_dir ${data.processed_dir}
      --val_ratio ${preprocess.val_ratio}
      --seed ${preprocess.seed}
      --angle_thresh ${preprocess.angle_thresh}
      --heatmap_resolution ${preprocess.heatmap_resolution}
      --input_resolution_h ${preprocess.input_resolution_h}
      --input_resolution_w ${preprocess.input_resolution_w}
    deps:
      - dataset/weld.py
      - ${data.label_dir}
      - ${data.img_dir}
    outs:
      - ${data.processed_dir}

  train:
    cmd: >
      python train.py -d 0 -i HR config/model.yaml
      --params params.yaml
    deps:
      - train.py
      - FClip
      - config/model.yaml
      - params.yaml
      - ${data.processed_dir}
    outs:
      - logs/IQI/${train.run_name}/checkpoint_best.pth.tar
      - logs/IQI/${train.run_name}/checkpoint_lastest.pth.tar
      - logs/IQI/${train.run_name}/config.yaml
    metrics:
      - logs/IQI/${train.run_name}/metrics.json:
          cache: false
    plots:
      - logs/IQI/${train.run_name}/loss.csv:
          x: progress
          y: sum
      - logs/IQI/${train.run_name}/train_loss.csv:
          x: progress
          y: sum
      - logs/IQI/${train.run_name}/precision.csv:
          x: progress
          y: precision
