stages:
  weld:
    cmd: >
      python dataset/weld.py
      --label_dir IQIdata/ori/label
      --img_dir IQIdata/ori/img
      --out_dir ${train.datadir}
      --val_ratio ${weld.val_ratio}
      --seed ${weld.seed}
      --angle_thresh ${weld.angle_thresh}
    deps:
      - dataset/weld.py
      - IQIdata/ori/label
      - IQIdata/ori/img
    outs:
      - ${train.datadir}

  train:
    cmd: >
      python train.py -d 0 -i HR config/fclip_HR.yaml
      --datadir ${train.datadir}
      --logdir ${train.logdir}
      --run_name ${train.run_name}
      --batch_size ${train.batch_size}
      --eval_batch_size ${train.eval_batch_size}
      --lr ${train.lr}
      --max_epoch ${train.max_epoch}
      --metrics_path ${train.metrics_path}
    deps:
      - train.py
      - FClip
      - config/fclip_HR.yaml
      - IQIdata/processed
    outs:
      - logs/IQI/${train.run_name}/checkpoint_best.pth.tar
      - logs/IQI/${train.run_name}/checkpoint_lastest.pth.tar
      - logs/IQI/${train.run_name}/config.yaml
    metrics:
      - ${train.metrics_path}
    plots:
      - logs/IQI/${train.run_name}/loss.csv:
          x: progress
          y: sum
      - logs/IQI/${train.run_name}/train_loss.csv:
          x: progress
          y: sum
