data:
  label_dir: IQIdata/ori/label
  img_dir: IQIdata/ori/img
  processed_dir: IQIdata/processed
  dataname: IQI

preprocess:
  heatmap_resolution: 64
  input_resolution_h: 256
  input_resolution_w: 256
  val_ratio: 0.1
  seed: 0
  angle_thresh: 50
  crop: true
  crop_factor: 1.2

train:
  logdir: logs/IQI
  run_name: iqi3_iqi_bo_t0012
  batch_size: 64
  eval_batch_size: 64
  lr: 0.004
  max_epoch: 400
  num_workers: 8
  validation_interval: 6400
  early_stop: 8
  visual_num: 2
  stage1: fclip
  delta: 0.8
  nlines: 7
  s_nms: 2

loss:
  lcmap_weight: 1.5
  lcoff_weight: 0.25
  lleng_weight: 0.0
  angle_weight: 1.0
  count_weight: 2.35
  count_sigma: 0.8

optim:
  name: Adam
  amsgrad: true
  weight_decay: 1.0e-4
  lr_scheduler: multi_step
  lr_decay_epoch:
  - 240
  - 280
