weld:
  val_ratio: 0.1
  seed: 0
  angle_thresh: 50

train:
  datadir: IQIdata/processed
  logdir: logs/IQI
  run_name: HR_exp_enhance_singlechannel
  batch_size: 16
  eval_batch_size: 2
  lr: 0.004
  max_epoch: 220
  metrics_path: metrics/HR_exp1.json
